"""edge-tts synthesis with an on-disk cache (CLAUDE.MD §5, §14).

Two reasons the cache matters more than it looks:

1. The four §14 hero lines are pre-generated at build time, so the opener
   ("मैं सुन रही हूँ — आप safe हैं") plays instantly. That sentence is the
   product's first impression and a two-second wait turns "someone is
   listening" into "a form is loading".
2. edge-tts is an unauthenticated network service. It will rate-limit, and it
   will be down at some point. A cache hit is the difference between a silent
   agent and a working one.

Voice casting per §5: Swara for the agent, Madhur for scammer scenario audio.
They must be clearly distinguishable, because a demo where both speakers sound
alike is impossible to follow.
"""

import asyncio
import hashlib
import logging
from pathlib import Path

import edge_tts

from app.config import Settings

log = logging.getLogger(__name__)

CACHE_DIR = Path(__file__).parent / "cache"

# §14. Agent voice (Swara). Pre-generated by scripts/build_tts_cache.py so
# these four never hit the network at runtime.
HERO_LINES = [
    "मैं सुन रही हूँ — आप safe हैं। आराम से बताइए क्या हुआ?",
    "वो OTP मुझे मत बताइए! सब आप खुद portal पे डालेंगी।",
    "पहला घंटा सबसे important है — मैं documents तैयार कर रही हूँ।",
    "Documents ready हैं — download कर लीजिए और 1930 पे file कर दीजिए।",
]


class TtsUnavailable(RuntimeError):
    """Synthesis failed and nothing was cached. Callers fall back to text."""


def cache_key(text: str, voice: str) -> str:
    """Voice is part of the key: the same line in two voices is two files."""
    return hashlib.md5(f"{voice}|{text}".encode("utf-8")).hexdigest()


def cached_path(text: str, voice: str) -> Path:
    return CACHE_DIR / f"{cache_key(text, voice)}.mp3"


async def synthesize(text: str, voice: str, *, timeout: float = 15.0) -> bytes:
    """Return MP3 bytes for this line, from cache when possible.

    A cached file is returned without any network call, so a rate-limited or
    unreachable edge-tts only affects lines nobody has spoken before.
    """
    if not text.strip():
        raise TtsUnavailable("empty text")

    path = cached_path(text, voice)
    if path.exists() and path.stat().st_size > 0:
        return path.read_bytes()

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    try:
        communicate = edge_tts.Communicate(text, voice)
        chunks: list[bytes] = []

        async def pull() -> None:
            async for chunk in communicate.stream():
                if chunk["type"] == "audio":
                    chunks.append(chunk["data"])

        await asyncio.wait_for(pull(), timeout=timeout)
    except Exception as exc:
        log.warning("edge-tts failed for %r: %s", text[:40], exc)
        raise TtsUnavailable(str(exc)) from exc

    audio = b"".join(chunks)
    if not audio:
        raise TtsUnavailable("edge-tts returned no audio")

    # Write via a temp file: a half-written mp3 left by a crash would be
    # served forever afterwards as a valid-looking cache hit.
    tmp = path.with_suffix(".part")
    tmp.write_bytes(audio)
    tmp.replace(path)
    return audio


async def warm_cache(settings: Settings) -> int:
    """Pre-generate the §14 hero lines. Returns how many are cached."""
    voice = settings.tts_voice_agent
    done = 0
    for line in HERO_LINES:
        try:
            await synthesize(line, voice)
            done += 1
        except TtsUnavailable as exc:
            log.warning("could not pre-cache %r: %s", line[:30], exc)
    return done
